app = "jacksonbryantportfolio-v2"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
